## playbook to set up workshop environment 

- hosts: xxx.xxx.xxx.xxx
  become: yes
  become_method: sudo 
  gather_facts: no
  tasks: 
     - include_tasks: yum.yml
     - include_tasks: users-groups.yml
     - include_tasks: move_files.yml
    
